[package]
name = "lgg-cli"
version = "0.1.1"
edition = "2024"

[dependencies]
lgg-core = { path = "../lgg-core" }
clap = { version = "4", features = ["derive", "env"] }
anyhow = "1.0.99"
tempfile = "3.20.0"
termimad = "0.34.0"
regex = "1.11.1"
